apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9qb2hua2F0dWE6c0lsektXbkJSa3hPV0FQcUBjbHVzdGVyMC5iNG92aGdq Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVy MA=="
  SECRET_KEY: <base64_encoded_secret_key>
  ALGORITHM: <base64_encoded_algorithm>
  ACCESS_TOKEN_EXPIRE_SECONDS: <base64_encoded_access_token_expire_seconds>
  DATABASE: <base64_encoded_database>
  CLIENT_ORIGIN: <base64_encoded_client_origin>

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakehouseenterprise-backend
  labels:
    app: lakehouseenterprise-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lakehouseenterprise-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: lakehouseenterprise-backend
    spec:
      containers:
      - name: lakehouseenterprise-backend
        image: <IMAGE_NAME>:<TAG>
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MONGO_URI

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: SECRET_KEY

        - name : ALGORITHM
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: ALGORITHM

        - name : ACCESS_TOKEN_EXPIRE_SECONDS
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: ACCESS_TOKEN_EXPIRE_SECONDS

        - name : DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE

        - name : CLIENT_ORIGIN
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: CLIENT_ORIGIN


        
    
---
apiVersion: v1
kind: Service
metadata:
  name: svc-lakehouseenterprise-backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: lakehouseenterprise-backend

