name: Deploy 
on:
  workflow_dispatch:
  push:
    branches:
      dev

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Run unit tests
        run: |
          echo "Running unit tests"
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
    steps:
      - name: Generate tag
        id: tag
        run: 
          echo "TAG=$(date +'%y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV  
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lakehouseenterprise-backend:latest
          

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: '${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
  
    - name: Update deployment file
      run: |
        sed -i "s|<IMAGE_NAME>:<TAG>|nexttechglobe/lakehouseenterprise-backend:latest|g" $GITHUB_WORKSPACE/config/deployment.yaml
        cat $GITHUB_WORKSPACE/config/deployment.yaml
    - name: Image path
      run : |
          echo  ${{ secrets.DOCKER_USERNAME }}/lakehouseenterprise-backend:latest

  
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: >-
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{secrets.CLUSTER_NAME }}
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        kubectl delete -f $GITHUB_WORKSPACE/config/deployment.yaml
        kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yaml
    - name: Verify deployment
      run: kubectl rollout status deployment/lakehouseenterprise-backend


















